'''
Created on 2018年9月15日

@author: jrq
'''


SMTP = 'smtp'
MQTT = 'mqtt'

SECTION_SEPARATOR = '.'
CLOUD = 'cloud'




SMTP_CLOUD_SECTION = SMTP + SECTION_SEPARATOR + CLOUD
MQTT_CLOUD_SECTION = MQTT + SECTION_SEPARATOR + CLOUD

HOST_KEY = 'smtp.163.com'
PORT_KEY = '587'
FROM_ADDRESS_KEY = 'A6178382877@163.com'
TO_ADDRESS_KEY = 'jiangruiqing1023@gmail.com'
USER_AUTH_TOKEN_KEY = '123qwe'

